module.exports = (sequelize, DataTypes) => {
  const KioskRegistration = sequelize.define('KioskRegistration', {
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true
  },
  token: {
    type: DataTypes.STRING(32),
    allowNull: false,
    unique: true,
    field: 'token',
    comment: 'Unique token generated by kiosk for registration (12+ alphanumeric)'
  },
  kioskId: {
    type: DataTypes.STRING(64),
    allowNull: false,
    field: 'kiosk_id',
    comment: 'Unique identifier for the kiosk (e.g., MAC address, device ID)'
  },
  status: {
    type: DataTypes.ENUM('pending', 'active', 'inactive'),
    allowNull: false,
    defaultValue: 'pending',
    field: 'status',
    comment: 'Registration status: pending (waiting for admin), active, inactive'
  },
  sessionId: {
    type: DataTypes.STRING,
    allowNull: true,
    field: 'session_id',
    comment: 'Session ID this kiosk is connected to'
  },
  registeredAt: {
    type: DataTypes.DATE,
    allowNull: false,
    defaultValue: DataTypes.NOW,
    field: 'registered_at',
    comment: 'When kiosk first registered'
  },
  activatedAt: {
    type: DataTypes.DATE,
    allowNull: true,
    field: 'activated_at',
    comment: 'When admin activated this kiosk'
  },
  lastHeartbeat: {
    type: DataTypes.DATE,
    allowNull: true,
    field: 'last_heartbeat',
    comment: 'Last time kiosk checked connection status'
  },
  kioskName: {
    type: DataTypes.STRING,
    allowNull: true,
    field: 'kiosk_name',
    comment: 'Optional friendly name for the kiosk'
  }
}, {
  tableName: 'kiosk_registrations',
  timestamps: true,
  underscored: true,
  indexes: [
    {
      unique: true,
      fields: ['token']
    },
    {
      fields: ['kiosk_id']
    },
    {
      fields: ['status']
    },
    {
      fields: ['session_id']
    }
  ]
});

  return KioskRegistration;
};
